spring:
  datasource:
    url: jdbc:postgresql://postgres:2Bu8T1dwLFOKkjXDZj7U@containers-us-west-191.railway.app:7990/railway
    username: postgres
    password: 2Bu8T1dwLFOKkjXDZj7U
    driverClassName: org.postgresql.Driver
    name: spring-blog
  sql:
    init:
      platform: postgres
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
debug: false
server:
  port: 8080

bezkoder:
  app:
    jwtCookieName: bezkoder
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 86400000
# The following is standard Spring Security OAuth2 configuration.
# App Properties

#  bezkoder.app.jwtSecret= bezKoderSecretKey
#  bezkoder.app.jwtExpirationMs= 86400000